name: apiverve_airquality
description: Air Quality is a simple tool for getting air quality data. It returns the air quality index, o3, pm2, and more.
version: 1.1.13
homepage: https://airquality.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/airquality-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
